name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # or the specific test command for your project

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Streamlit
        env:
          STREAMLIT_EMAIL: ${{ secrets.STREAMLIT_EMAIL }}
          STREAMLIT_PASSWORD: ${{ secrets.STREAMLIT_PASSWORD }}
        run: |
          streamlit run app.py  # Replace `app.py` with your main Streamlit app file

  mlops:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MLOps Pipeline
        run: |
          # Your specific MLOps commands, e.g., triggering MLFlow, ZenML, etc.
          python run_mlops_pipeline.py  # Adjust according to your MLOps pipeline script
